import { PDFDocument, rgb, StandardFonts, PDFPage } from "pdf-lib";
import type { CompanyProfile, PdfTemplate } from "@/types";

interface PdfOptions {
  template: PdfTemplate;
  company: CompanyProfile;
  title: string;
  filename: string;
}

function getTemplateColors(template: PdfTemplate) {
  switch (template) {
    case "modern":
      return {
        primary: rgb(0.2, 0.4, 0.8),
        secondary: rgb(0.95, 0.95, 1),
        text: rgb(0.1, 0.1, 0.1),
        lightText: rgb(0.5, 0.5, 0.5),
      };
    case "professional":
      return {
        primary: rgb(0.1, 0.1, 0.1),
        secondary: rgb(0.95, 0.95, 0.95),
        text: rgb(0.1, 0.1, 0.1),
        lightText: rgb(0.4, 0.4, 0.4),
      };
    case "minimal":
      return {
        primary: rgb(0.3, 0.3, 0.3),
        secondary: rgb(0.98, 0.98, 0.98),
        text: rgb(0.2, 0.2, 0.2),
        lightText: rgb(0.6, 0.6, 0.6),
      };
  }
}

export async function createPdfDocument(options: PdfOptions) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  return { pdfDoc, font, fontBold, colors: getTemplateColors(options.template) };
}

export function addHeader(
  page: PDFPage,
  company: CompanyProfile,
  title: string,
  font: any,
  fontBold: any,
  colors: ReturnType<typeof getTemplateColors>,
  y: number
) {
  const { width } = page.getSize();

  // Company name
  page.drawText(company.companyName || "Your Company", {
    x: 50,
    y,
    size: 18,
    font: fontBold,
    color: colors.primary,
  });

  // Company details
  let detailY = y - 20;
  const details = [
    company.address,
    company.phone && `Phone: ${company.phone}`,
    company.email && `Email: ${company.email}`,
    company.website && company.website,
    company.taxId && `Tax ID: ${company.taxId}`,
  ].filter(Boolean);

  for (const detail of details) {
    page.drawText(detail, {
      x: 50,
      y: detailY,
      size: 9,
      font,
      color: colors.lightText,
    });
    detailY -= 14;
  }

  // Title
  page.drawText(title, {
    x: width - 50 - font.widthOfTextAtSize(title, 24),
    y: y,
    size: 24,
    font: fontBold,
    color: colors.primary,
  });

  return detailY - 20;
}

export function addFooter(
  page: PDFPage,
  company: CompanyProfile,
  font: any,
  colors: ReturnType<typeof getTemplateColors>
) {
  const { width, height } = page.getSize();

  // Signature line
  if (company.signatoryName) {
    const sigY = 120;
    page.drawText("Authorized Signature:", {
      x: width - 200,
      y: sigY + 40,
      size: 9,
      font,
      color: colors.lightText,
    });
    page.drawLine({
      start: { x: width - 200, y: sigY + 30 },
      end: { x: width - 50, y: sigY + 30 },
      thickness: 0.5,
      color: colors.lightText,
    });
    page.drawText(company.signatoryName, {
      x: width - 200,
      y: sigY + 15,
      size: 10,
      font,
      color: colors.text,
    });
    if (company.signatoryPosition) {
      page.drawText(company.signatoryPosition, {
        x: width - 200,
        y: sigY,
        size: 9,
        font,
        color: colors.lightText,
      });
    }
  }

  // Footer text
  page.drawText(`Generated by Lumizo Docs`, {
    x: 50,
    y: 40,
    size: 8,
    font,
    color: colors.lightText,
  });
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}
