import { PDFDocument, rgb, StandardFonts, type PDFPage } from "pdf-lib";
import type { CompanyProfile } from "@/types";

export const base64ToUint8Array = (base64: string): Uint8Array => {
  const arr = base64.split(",");
  const bstr = atob(arr[1]);
  let n = bstr.length;
  const u8arr = new Uint8Array(n);
  while (n--) {
    u8arr[n] = bstr.charCodeAt(n);
  }
  return u8arr;
};

export const colors = {
  primary: rgb(0.2, 0.4, 0.8),
  text: rgb(0.1, 0.1, 0.1),
  lightText: rgb(0.5, 0.5, 0.5),
  green: rgb(0.1, 0.6, 0.3),
  red: rgb(0.8, 0.2, 0.2),
};

export interface DrawCompanyHeaderOptions {
  page: PDFPage;
  profile: CompanyProfile;
  y: number;
  title: string;
}

export const drawCompanyHeader = async ({
  page,
  profile,
  y,
  title,
}: DrawCompanyHeaderOptions): Promise<number> => {
  const font = await page.doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await page.doc.embedFont(StandardFonts.HelveticaBold);

  let x = 50;

  // Embed logo if available
  if (profile.logo) {
    try {
      const logoBytes = base64ToUint8Array(profile.logo);
      const logoImage = await page.doc.embedPng(logoBytes);
      const logoWidth = 60;
      const logoHeight = (logoImage.height / logoImage.width) * logoWidth;
      page.drawImage(logoImage, {
        x: 50,
        y: y - logoHeight + 10,
        width: logoWidth,
        height: logoHeight,
      });
      x = 50 + logoWidth + 15;
    } catch (e) {
      console.error("Failed to embed logo:", e);
    }
  }

  // Company name
  page.drawText(profile.companyName || "Your Company", {
    x,
    y,
    size: 18,
    font: fontBold,
    color: colors.primary,
  });
  y -= 20;

  // Company details
  if (profile.address) {
    page.drawText(profile.address, { x, y, size: 9, font, color: colors.lightText });
    y -= 12;
  }
  if (profile.phone) {
    page.drawText(`Phone: ${profile.phone}`, { x, y, size: 9, font, color: colors.lightText });
    y -= 12;
  }
  if (profile.email) {
    page.drawText(`Email: ${profile.email}`, { x, y, size: 9, font, color: colors.lightText });
    y -= 12;
  }

  // Title
  page.drawText(title, {
    x: 400,
    y: 770,
    size: 28,
    font: fontBold,
    color: colors.primary,
  });

  return y;
};

export const drawSignature = async (
  page: PDFPage,
  profile: CompanyProfile,
  y: number
) => {
  const font = await page.doc.embedFont(StandardFonts.Helvetica);
  if (profile.signatoryName) {
    const sigY = y;
    page.drawText("Authorized Signature:", {
      x: 370,
      y: sigY + 20,
      size: 9,
      font,
      color: colors.lightText,
    });
    page.drawLine({
      start: { x: 370, y: sigY + 10 },
      end: { x: 545, y: sigY + 10 },
      thickness: 0.5,
      color: colors.lightText,
    });
    page.drawText(profile.signatoryName, {
      x: 370,
      y: sigY - 5,
      size: 9,
      font,
      color: colors.text,
    });
  }
};

export const drawFooter = async (page: PDFPage) => {
  const font = await page.doc.embedFont(StandardFonts.Helvetica);
  page.drawText("Generated by Lumizo Docs", {
    x: 50,
    y: 50,
    size: 8,
    font,
    color: colors.lightText,
  });
};
